In [1]:
import requests
import json
import keyring
import pandas as pd
import time
import numpy as np
import datetime
from datetime import timedelta
import schedule
import urllib3

urllib3.disable_warnings()
keyring.set_password('mock_app_key', 'jhsong89', 'PSKvVlB2F0JNa5eijhXpvUcGjIzBqnMZvYXw')
keyring.set_password('mock_app_secret', 'jhsong89', 'iaDjbMg+kKdWz/DrH7F/Uy77XRonC/E4P/jaeSfR/u4GK1/W2OKURleZjWgr5KUgtpYfIZYGPb+FukOsivQNOQuB7X3rfDu3XCtqbwFRbMC30BsyhSudQZw6G+9SF4nKEpKT9cBcqSE/KZmM/sVAaIhvRj8jJSyYhZymhq483oztqNAHZWg=')

# API Key
app_key = keyring.get_password('mock_app_key', 'jhsong89')
app_secret = keyring.get_password('mock_app_secret', 'jhsong89')

# 접근토큰 발급
url_base = "https://openapivts.koreainvestment.com:29443"  # 모의투자

headers = {"content-type": "application/json"}
path = "oauth2/tokenP"
body = {
    "grant_type": "client_credentials",
    "appkey": app_key,
    "appsecret": app_secret
}

url = f"{url_base}/{path}"
res = requests.post(url, headers=headers, data=json.dumps(body), verify=False)
access_token = res.json()['access_token']

# 해시키 발급
def hashkey(datas):
    path = "uapi/hashkey"
    url = f"{url_base}/{path}"
    headers = {
        'content-Type': 'application/json',
        'appKey': app_key,
        'appSecret': app_secret,
    }
    res = requests.post(url, headers=headers, data=json.dumps(datas), verify=False)
    hashkey = res.json()["HASH"]

    return hashkey

# 현재가 구하기
def get_price(ticker):
    path = "uapi/domestic-stock/v1/quotations/inquire-price"
    url = f"{url_base}/{path}"

    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {access_token}",
        "appKey": app_key,
        "appSecret": app_secret,
        "tr_id": "FHKST01010100"
    }

    params = {"fid_cond_mrkt_div_code": "J", "fid_input_iscd": ticker}

    res = requests.get(url, headers=headers, params=params, verify=False)
    price = res.json()['output']['stck_prpr']
    price = int(price)
    time.sleep(0.5)

    return price

# 주문
#종목코드에 해당하는 ticker와 매수/매도 구분에 해당하는 tr_id를 입력하면, 
#해당 종목을 최유리 지정가(ORD_DVSN)로 한 주씩(ORD_QTY) 주문을 낸다
def trading(ticker, tr_id):

    path = "/uapi/domestic-stock/v1/trading/order-cash"
    url = f"{url_base}/{path}"

    data = {
        "CANO": "50146217", # 계좌번호 앞 8지리
        "ACNT_PRDT_CD": "01",   # 계좌번호 뒤 2자리
        "PDNO": ticker,     # 종목코드
        "ORD_DVSN": "01",  # 주문방법(00:지정가,01:시장가,02:조건부지정가,03:최유리지정가,04:최우선지정가,...)
        "ORD_QTY": "1",    #한주씩은 시간이 걸려 10주로 변경
        "ORD_UNPR": "0",    # 주문 단가 (시장가의 경우 0)
    }

    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {access_token}",
        "appKey": app_key,
        "appSecret": app_secret,
        "tr_id": tr_id,     # 모의투자 'VTTC0802U' (현금매수) if n > 0 else 'VTTC0801U' (현금매도)
        "custtype": "P",
        "hashkey": hashkey(data)
    }

    res = requests.post(url, headers=headers, data=json.dumps(data), verify=False)
    
# 계좌 잔고 조회
#계좌의 보유종목 및 계좌잔고 항목을 조회하는 함수
#잔고조회 API는 모의투자에서는 한번에 20종목까지, 실제계좌에서는 50종목까지 조회가 가능
def check_account():

    output1 = []
    output2 = []
    CTX_AREA_NK100 = ''

    while True:

        path = "/uapi/domestic-stock/v1/trading/inquire-balance"
        url = f"{url_base}/{path}"

        headers = {
            "Content-Type": "application/json",
            "authorization": f"Bearer {access_token}",
            "appKey": app_key,
            "appSecret": app_secret,
            "tr_id": "VTTC8434R"
        }

        params = {
            "CANO": "50146217",     # 계좌번호 앞 8지리
            "ACNT_PRDT_CD": "01",   # 계좌번호 뒤 2자리
            "AFHR_FLPR_YN": "N",    # 시간외단일가여부 
            "UNPR_DVSN": "01",      # 단가구분
            "FUND_STTL_ICLD_YN": "N",       # 펀드결제분포함여부
            "FNCG_AMT_AUTO_RDPT_YN": "N",   # 융자금액자동상환여부     
            "OFL_YN": "",           # 공란
            "INQR_DVSN": "01",      # 조회구분
            "PRCS_DVSN": "00",      # 처리구분(00: 전일매매포함)
            "CTX_AREA_FK100": '',   # 연속조회검색조건
            "CTX_AREA_NK100": CTX_AREA_NK100    # 연속조회키
        }

        res = requests.get(url, headers=headers, params=params, verify=False)
        output1.append(pd.DataFrame.from_records(res.json()['output1']))

#연속조회 값이 없을경우 res.json()['ctx_area_nk100'] 값은 ''
        CTX_AREA_NK100 = res.json()['ctx_area_nk100'].strip()

        if CTX_AREA_NK100 == '':
            output2.append(res.json()['output2'][0])
            break

    if not output1[0].empty:
        res1 = pd.concat(output1)[['pdno',
                                   'hldg_qty']].rename(columns={
                                       'pdno': '종목코드',
                                       'hldg_qty': '보유수량'
                                   }).reset_index(drop=True)
    else:
        res1 = pd.DataFrame(columns=['종목코드', '보유수량'])

# res2에는 계좌잔고를 입력
    res2 = output2[0]

    return [res1, res2]

In [2]:
#보유종목에 해당하는 res1은 ap 변수에, 계좌잔고에 해당하는 res2는account 변수에 각각 입력
ap, account = check_account()

# 모델 포트폴리오
#모델 포트폴리오는 ‘멀티팩터 포트폴리오’ 구성을 통해 나온 결과를 사용
#새롭게 투자해야 할 종목은 보유수량이 0이며, 
#총평가금액을 이용해 목표수량과 투자수량이계산된다. 
#반면 제외되는 종목은 목표수량이 0이며, 투자수량 만큼 매도를 한다. 
#이를 토대로시분할 주문을 스케줄에 입력한다. 
#9시 10분이 되면 스케줄에 따라 매수와 매도가 동시에 일어나며 리밸런싱 작업이 진행
mp = pd.read_excel('D:/model.xlsx', dtype=str)

# 보유종목과 aum 불러오기
ap, account = check_account()

In [3]:
# 주당 투자 금액
#계좌잔고에서 총평가금액 항목을 가져온 후 int() 함수를 통해 숫자형태로 변경
#총평가금액을 100% 투자할 경우, 리밸런싱 과정에서 주가의 등락에 의해 주문금액이 보유금액을 초과가능
#1~5% 정도의 현금은 보유 (즉 총평가금액의 98%만 투자에 이용)
#모델 포트폴리오의 종목수로 나누어 종목당 투자 금액을 계산
invest_per_stock = int(account['tot_evlu_amt']) * 0.8 / len(mp)

# 매매 구성
#투자하고자 하는 포트폴리오(mp)와 현재 포트폴리오(ap)를 merge()함수를 통해 합치며,
#모든 종목이 들어가야 하므로 outer 방식으로 합친다.
target = mp.merge(ap, on='종목코드', how='outer')
#mp 중 현재 보유하고 있지 않은 종목은 NA로 표시되므로, 이를 0으로 바꾼다
# ‘보유수량’열의 값을 to_numeric() 함수를 이용해 숫자형태로 변경
target['보유수량'] = target['보유수량'].fillna(0).apply(pd.to_numeric)

# 현재가 확인
#현재가를 확인하는 get_price() 함수를 이용해 모든 종목의 현재가를 확인
target['현재가'] = target.apply(lambda x: get_price(x.종목코드), axis=1)

# 목표수량 및 투자수량 입력
# ‘종목당 투자 금액/현재가’를 통해 종목당 목표수량이 얼마인지 계산한
target['목표수량'] = np.where(target['종목코드'].isin(mp['종목코드'].tolist()),
                          round(invest_per_stock / target['현재가']), 0)
#목표수량에서 보유수량을 빼 실제로 몇주를 투자해야 하는지 계산
target['투자수량'] = target['목표수량'] - target['보유수량']

target

,종목코드,구분,종목명,보유수량,현재가,목표수량,투자수량
0,003230,"k_ratio_12,quality,quality4",삼양식품,15,1383000,20.0,5.0
1,004800,NaN,NaN,62,100900,0.0,-62.0
2,005440,"multi_factor4,per_pbr",현대지에프홀딩스,2153,7940,3445.0,1292.0
3,010140,"k_ratio_12,k_ratio_6",삼성중공업,747,22550,1213.0,466.0
4,012750,"k_ratio_3,k_ratio_6",에스원,211,75700,361.0,150.0
5,018290,"quality,quality4",브이티,826,26100,1048.0,222.0
6,028050,NaN,NaN,44,27350,0.0,-44.0
7,030200,NaN,NaN,23,50100,0.0,-23.0
8,032640,"multi_factor,multi_factor4",LG유플러스,1528,15180,1802.0,274.0
9,033100,"magic_rank,quality,quality4",제룡전기,652,36800,743.0,91.0
10,067160,"quality,quality4",SOOP,295,72800,376.0,81.0
11,084110,"multi_factor,multi_factor4",휴온스글로벌,475,55100,496.0,21.0
12,087010,NaN,NaN,4,268000,0.0,-4.0
13,127120,"k_ratio_12,k_ratio_3",제이에스링크,1036,20900,1309.0,273.0
14,214450,NaN,NaN,11,600000,0.0,-11.0
15,278470,"k_ratio_6,quality,quality4",에이피알,97,236000,116.0,19.0
16,335890,"quality,quality4",비올,1580,12420,2202.0,622.0
17,372320,"k_ratio_3,k_ratio_6",큐로셀,408,38900,703.0,295.0
18,403870,"quality,quality4",HPSP,660,36150,757.0,97.0
19,458870,"k_ratio_3,k_ratio_6",씨어스테크놀로지,243,70700,387.0,144.0

In [4]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:jhsong89@127.0.0.1:3306/stock_db')

sector_list = pd.read_sql("""
select * from kor_sector
where 기준일 = (select max(기준일) from kor_ticker);	
""", con=engine)

#먼저 가격 테이블을 이용해 최근 12개월 수익률을 구한다. 또한 로그 누적수익률을 통해 각 종목 별 K-Ratio를 계산한다.
kor_target = target[['종목코드','현재가','보유수량','목표수량','투자수량']].merge(
    sector_list[['CMP_CD', 'CMP_KOR', 'SEC_NM_KOR']],
    how='left',
    left_on='종목코드',
    right_on='CMP_CD')

kor_target.loc[kor_target['SEC_NM_KOR'].isnull(), 'SEC_NM_KOR'] = '기타'
kor_target = kor_target.drop(['CMP_CD'], axis=1)

#target  # 만들어진 데이터프레임 확인
kor_target

      종목코드      현재가  보유수량    목표수량    투자수량   CMP_KOR SEC_NM_KOR
0   003230  1383000    15    20.0     5.0      삼양식품      필수소비재
1   004800   100900    62     0.0   -62.0        효성        산업재
2   005440     7940  2153  3445.0  1292.0  현대지에프홀딩스        산업재
3   010140    22550   747  1213.0   466.0     삼성중공업        산업재
4   012750    75700   211   361.0   150.0       에스원        산업재
5   018290    26100   826  1048.0   222.0       브이티    경기관련소비재
6   028050    27350    44     0.0   -44.0     삼성E&A        산업재
7   030200    50100    23     0.0   -23.0        KT  커뮤니케이션서비스
8   032640    15180  1528  1802.0   274.0    LG유플러스  커뮤니케이션서비스
9   033100    36800   652   743.0    91.0      제룡전기        산업재
10  067160    72800   295   376.0    81.0      SOOP  커뮤니케이션서비스
11  084110    55100   475   496.0    21.0    휴온스글로벌       건강관리
12  087010   268000     4     0.0    -4.0       펩트론       건강관리
13  127120    20900  1036  1309.0   273.0    제이에스링크       건강관리
14  214450   600000    11     0.0   -11.0     파마리서치       건강관리
15  278470   236000    97   116.0    19.0      에이피알    경기관련소비재
16  335890    12420  1580  2202.0   622.0        비올       건강관리
17  372320    38900   408   703.0   295.0       큐로셀       건강관리
18  403870    36150   660   757.0    97.0      HPSP         IT
19  458870    70700   243   387.0   144.0  씨어스테크놀로지       건강관리

In [5]:
##=========================================
kor_target.to_excel('D:/Target.xlsx', index=False)

from sqlalchemy import create_engine
#SQL에는 NaN이 입력되지 않으므로, None으로 변경한다.
engine = create_engine('mysql+pymysql://root:jhsong89@127.0.0.1:3306/stock_db')
kor_target = kor_target.round(4).replace({np.nan: None})
kor_target.to_sql(name='target', con=engine, index=False, if_exists='replace')

20

In [6]:
##==========================================   
# 시간 분할
#시작시간(startDt)은 현재보다 1분 뒤와 9시 10분 중 큰 값을 선택
startDt1 = datetime.datetime.now() + timedelta(minutes=1)
startDt2 = datetime.datetime.now().replace(hour=9,minute=10,second=0,microsecond=0)
startDt = max(startDt1, startDt2)
#종료시간(endDt)는 오후 3시를 입력
endDt1 = datetime.datetime.now() + timedelta(minutes=30)
endDt2 = datetime.datetime.now().replace(hour=12,minute=00,second=0,microsecond=0)
endDt = min(endDt1, endDt2)

# 스케줄 초기화
schedule.clear()    #기존 등록된 스케줄을 모두 삭제

In [7]:
# 스케줄 등록
# for문을 통해 전 종목의 시분할 주문을 만든다
for t in range(target.shape[0]) :
    
    #투자수량(n)이 0보다클 경우 매수를 해야하므로 이에 해당하는 tr_id인 ‘VTTC0802U’을, 
    #매도의 경우에는 ‘VTTC0801U’를 입력
    n = target.loc[t, '투자수량']
    position = 'VTTC0802U' if n > 0 else 'VTTC0801U'
    ticker = target.loc[t, '종목코드']    
    
    #시작시간부터 종료시간까지 투자수량의 절댓값에 해당하는 만큼 기간을 나눈다. 
    #이 후 ‘시:분:초’의 형태로 만든다
    time_list = pd.date_range(startDt, endDt, periods = abs(n))    
    time_list = time_list.round(freq = 's').tolist()    
    time_list_sec = [s.strftime('%H:%M:%S') for s in time_list]                 

    #스케줄러에 등록될 함수에 인자가 들어가는 경우는 
    #do(함수명, 인자1, 인자2,...) 형태로 입력
    for i in time_list_sec:
        schedule.every().day.at(i).do(trading, ticker, position)   

#모든 종목이 한 주씩 시분할 주문이 나가도록 스케줄이 등록되어 있다.
schedule.get_jobs()

C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))
C:\Users\USER\AppData\Local\Temp\ipykernel_11172\4086506931.py:13: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  time_list = pd.date_range(startDt, endDt, periods = abs(n))

[Every 1 day at 11:23:47 do trading('003230', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:47),
 Every 1 day at 11:31:02 do trading('003230', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:31:02),
 Every 1 day at 11:38:17 do trading('003230', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:38:17),
 Every 1 day at 11:45:32 do trading('003230', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:45:32),
 Every 1 day at 11:52:47 do trading('003230', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:52:47),
 Every 1 day at 11:23:47 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:23:47),
 Every 1 day at 11:24:16 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:24:16),
 Every 1 day at 11:24:44 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:24:44),
 Every 1 day at 11:25:13 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:25:13),
 Every 1 day at 11:25:41 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:25:41),
 Every 1 day at 11:26:10 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:26:10),
 Every 1 day at 11:26:38 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:26:38),
 Every 1 day at 11:27:07 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:27:07),
 Every 1 day at 11:27:35 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:27:35),
 Every 1 day at 11:28:04 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:28:04),
 Every 1 day at 11:28:33 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:28:33),
 Every 1 day at 11:29:01 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:29:01),
 Every 1 day at 11:29:30 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:29:30),
 Every 1 day at 11:29:58 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:29:58),
 Every 1 day at 11:30:27 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:30:27),
 Every 1 day at 11:30:55 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:30:55),
 Every 1 day at 11:31:24 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:31:24),
 Every 1 day at 11:31:52 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:31:52),
 Every 1 day at 11:32:21 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:32:21),
 Every 1 day at 11:32:49 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:32:49),
 Every 1 day at 11:33:18 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:33:18),
 Every 1 day at 11:33:46 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:33:46),
 Every 1 day at 11:34:15 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:34:15),
 Every 1 day at 11:34:43 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:34:43),
 Every 1 day at 11:35:12 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:35:12),
 Every 1 day at 11:35:40 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:35:40),
 Every 1 day at 11:36:09 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:36:09),
 Every 1 day at 11:36:37 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:36:37),
 Every 1 day at 11:37:06 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:37:06),
 Every 1 day at 11:37:34 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:37:34),
 Every 1 day at 11:38:03 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:38:03),
 Every 1 day at 11:38:32 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:38:32),
 Every 1 day at 11:39:00 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:39:00),
 Every 1 day at 11:39:29 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:39:29),
 Every 1 day at 11:39:57 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:39:57),
 Every 1 day at 11:40:26 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:40:26),
 Every 1 day at 11:40:54 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:40:54),
 Every 1 day at 11:41:23 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:41:23),
 Every 1 day at 11:41:51 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:41:51),
 Every 1 day at 11:42:20 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:42:20),
 Every 1 day at 11:42:48 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:42:48),
 Every 1 day at 11:43:17 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:43:17),
 Every 1 day at 11:43:45 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:43:45),
 Every 1 day at 11:44:14 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:44:14),
 Every 1 day at 11:44:42 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:44:42),
 Every 1 day at 11:45:11 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:45:11),
 Every 1 day at 11:45:39 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:45:39),
 Every 1 day at 11:46:08 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:46:08),
 Every 1 day at 11:46:36 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:46:36),
 Every 1 day at 11:47:05 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:47:05),
 Every 1 day at 11:47:34 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:47:34),
 Every 1 day at 11:48:02 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:48:02),
 Every 1 day at 11:48:31 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:48:31),
 Every 1 day at 11:48:59 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:48:59),
 Every 1 day at 11:49:28 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:49:28),
 Every 1 day at 11:49:56 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:49:56),
 Every 1 day at 11:50:25 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:50:25),
 Every 1 day at 11:50:53 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:50:53),
 Every 1 day at 11:51:22 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:51:22),
 Every 1 day at 11:51:50 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:51:50),
 Every 1 day at 11:52:19 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:52:19),
 Every 1 day at 11:52:47 do trading('004800', 'VTTC0801U') (last run: [never], next run: 2025-10-20 11:52:47),
 Every 1 day at 11:23:47 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:47),
 Every 1 day at 11:23:49 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:49),
 Every 1 day at 11:23:50 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:50),
 Every 1 day at 11:23:51 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:51),
 Every 1 day at 11:23:53 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:53),
 Every 1 day at 11:23:54 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:54),
 Every 1 day at 11:23:55 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:55),
 Every 1 day at 11:23:57 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:57),
 Every 1 day at 11:23:58 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:58),
 Every 1 day at 11:23:59 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:23:59),
 Every 1 day at 11:24:01 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:01),
 Every 1 day at 11:24:02 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:02),
 Every 1 day at 11:24:03 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:03),
 Every 1 day at 11:24:05 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:05),
 Every 1 day at 11:24:06 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:06),
 Every 1 day at 11:24:08 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:08),
 Every 1 day at 11:24:09 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:09),
 Every 1 day at 11:24:10 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:10),
 Every 1 day at 11:24:12 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:12),
 Every 1 day at 11:24:13 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:13),
 Every 1 day at 11:24:14 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:14),
 Every 1 day at 11:24:16 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:16),
 Every 1 day at 11:24:17 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:17),
 Every 1 day at 11:24:18 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:18),
 Every 1 day at 11:24:20 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:20),
 Every 1 day at 11:24:21 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:21),
 Every 1 day at 11:24:22 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:22),
 Every 1 day at 11:24:24 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:24),
 Every 1 day at 11:24:25 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:25),
 Every 1 day at 11:24:26 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:26),
 Every 1 day at 11:24:28 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:28),
 Every 1 day at 11:24:29 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:29),
 Every 1 day at 11:24:30 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:30),
 Every 1 day at 11:24:32 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:32),
 Every 1 day at 11:24:33 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:33),
 Every 1 day at 11:24:34 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:34),
 Every 1 day at 11:24:36 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:36),
 Every 1 day at 11:24:37 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:37),
 Every 1 day at 11:24:39 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:39),
 Every 1 day at 11:24:40 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:40),
 Every 1 day at 11:24:41 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:41),
 Every 1 day at 11:24:43 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:43),
 Every 1 day at 11:24:44 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:44),
 Every 1 day at 11:24:45 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:45),
 Every 1 day at 11:24:47 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:47),
 Every 1 day at 11:24:48 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:48),
 Every 1 day at 11:24:49 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:49),
 Every 1 day at 11:24:51 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:51),
 Every 1 day at 11:24:52 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:52),
 Every 1 day at 11:24:53 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:53),
 Every 1 day at 11:24:55 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:55),
 Every 1 day at 11:24:56 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:56),
 Every 1 day at 11:24:57 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:57),
 Every 1 day at 11:24:59 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:24:59),
 Every 1 day at 11:25:00 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:00),
 Every 1 day at 11:25:01 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:01),
 Every 1 day at 11:25:03 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:03),
 Every 1 day at 11:25:04 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:04),
 Every 1 day at 11:25:05 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:05),
 Every 1 day at 11:25:07 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:07),
 Every 1 day at 11:25:08 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:08),
 Every 1 day at 11:25:10 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:10),
 Every 1 day at 11:25:11 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:11),
 Every 1 day at 11:25:12 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:12),
 Every 1 day at 11:25:14 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:14),
 Every 1 day at 11:25:15 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:15),
 Every 1 day at 11:25:16 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:16),
 Every 1 day at 11:25:18 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:18),
 Every 1 day at 11:25:19 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:19),
 Every 1 day at 11:25:20 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:20),
 Every 1 day at 11:25:22 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:22),
 Every 1 day at 11:25:23 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:23),
 Every 1 day at 11:25:24 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:24),
 Every 1 day at 11:25:26 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:26),
 Every 1 day at 11:25:27 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:27),
 Every 1 day at 11:25:28 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:28),
 Every 1 day at 11:25:30 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:30),
 Every 1 day at 11:25:31 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:31),
 Every 1 day at 11:25:32 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:32),
 Every 1 day at 11:25:34 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:34),
 Every 1 day at 11:25:35 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:35),
 Every 1 day at 11:25:36 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:36),
 Every 1 day at 11:25:38 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:38),
 Every 1 day at 11:25:39 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:39),
 Every 1 day at 11:25:40 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:40),
 Every 1 day at 11:25:42 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:42),
 Every 1 day at 11:25:43 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:43),
 Every 1 day at 11:25:45 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:45),
 Every 1 day at 11:25:46 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:46),
 Every 1 day at 11:25:47 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:47),
 Every 1 day at 11:25:49 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:49),
 Every 1 day at 11:25:50 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:50),
 Every 1 day at 11:25:51 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:51),
 Every 1 day at 11:25:53 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:53),
 Every 1 day at 11:25:54 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:54),
 Every 1 day at 11:25:55 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:55),
 Every 1 day at 11:25:57 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:57),
 Every 1 day at 11:25:58 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:58),
 Every 1 day at 11:25:59 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:25:59),
 Every 1 day at 11:26:01 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:01),
 Every 1 day at 11:26:02 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:02),
 Every 1 day at 11:26:03 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:03),
 Every 1 day at 11:26:05 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:05),
 Every 1 day at 11:26:06 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:06),
 Every 1 day at 11:26:07 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:07),
 Every 1 day at 11:26:09 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:09),
 Every 1 day at 11:26:10 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:10),
 Every 1 day at 11:26:11 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:11),
 Every 1 day at 11:26:13 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:13),
 Every 1 day at 11:26:14 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:14),
 Every 1 day at 11:26:16 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:16),
 Every 1 day at 11:26:17 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:17),
 Every 1 day at 11:26:18 do trading('005440', 'VTTC0802U') (last run: [never], next run: 2025-10-20 11:26:18),

In [8]:
# 스케줄 실행
#schedule.run_pending() 함수를 통해 스케줄에 등록된 작업을 실행
#만일 현재시간이 3시(endDt) 이후 일 경우에는 스케줄을 모두 지우고 
#break를 통해 작업을 정지
while True:
    schedule.run_pending()    
    if datetime.datetime.now() > endDt :
        print('거래가 완료되었습니다.')        
        schedule.clear()
        break
    
#목표수량과 실제수량이 차이가 없는지 확인
#계좌정보를 확인하는 check_account() 함수를 통해 보유종목과 계좌잔고를 불러온다
ap_after, account_after = check_account()   
#보유종목 데이터프레임의 열 이름을 바꾼다.     
ap_after.columns  = ['종목코드', '매매후수량']
#‘매매후수량’열을 숫자 형태로 바꾼다.
ap_after['매매후수량'] = ap_after['매매후수량'].apply(pd.to_numeric)

#기존 데이터프레임과 합친다
target_after = kor_target.merge(ap_after)
#‘목표수량’과 ‘매매후수량’의 차이를 구한다.
target_after['차이'] = target_after['목표수량'] - target_after['매매후수량']

target_after

거래가 완료되었습니다.

      종목코드      현재가  보유수량    목표수량    투자수량   CMP_KOR SEC_NM_KOR  매매후수량     차이
0   003230  1383000    15    20.0     5.0      삼양식품      필수소비재     18    2.0
1   004800   100900    62     0.0   -62.0        효성        산업재     27  -27.0
2   005440     7940  2153  3445.0  1292.0  현대지에프홀딩스        산업재   2871  574.0
3   010140    22550   747  1213.0   466.0     삼성중공업        산업재   1011  202.0
4   012750    75700   211   361.0   150.0       에스원        산업재    296   65.0
5   018290    26100   826  1048.0   222.0       브이티    경기관련소비재    951   97.0
6   028050    27350    44     0.0   -44.0     삼성E&A        산업재     19  -19.0
7   030200    50100    23     0.0   -23.0        KT  커뮤니케이션서비스     10  -10.0
8   032640    15180  1528  1802.0   274.0    LG유플러스  커뮤니케이션서비스   1683  119.0
9   033100    36800   652   743.0    91.0      제룡전기        산업재    703   40.0
10  067160    72800   295   376.0    81.0      SOOP  커뮤니케이션서비스    341   35.0
11  084110    55100   475   496.0    21.0    휴온스글로벌       건강관리    487    9.0
12  087010   268000     4     0.0    -4.0       펩트론       건강관리      2   -2.0
13  127120    20900  1036  1309.0   273.0    제이에스링크       건강관리   1189  120.0
14  214450   600000    11     0.0   -11.0     파마리서치       건강관리      5   -5.0
15  278470   236000    97   116.0    19.0      에이피알    경기관련소비재    108    8.0
16  335890    12420  1580  2202.0   622.0        비올       건강관리   1853  349.0
17  372320    38900   408   703.0   295.0       큐로셀       건강관리    570  133.0
18  403870    36150   660   757.0    97.0      HPSP         IT    715   42.0
19  458870    70700   243   387.0   144.0  씨어스테크놀로지       건강관리    324   63.0